// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9ZznEAcSRWU3i5C3yAh8FeWfPgTBIlW0',
    appId: '1:797973623484:web:9308767f3d6476f30656b9',
    messagingSenderId: '797973623484',
    projectId: 'ltb-10',
    authDomain: 'ltb-10.firebaseapp.com',
    storageBucket: 'ltb-10.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqDGUf3YNCBwZcDpj6ouPS1trbpZk7poY',
    appId: '1:797973623484:android:6586a5e937240c230656b9',
    messagingSenderId: '797973623484',
    projectId: 'ltb-10',
    storageBucket: 'ltb-10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChr3tgmwgzlj2sT9Te9tzBZYOnrgKyOIs',
    appId: '1:797973623484:ios:57ba308e488485b90656b9',
    messagingSenderId: '797973623484',
    projectId: 'ltb-10',
    storageBucket: 'ltb-10.firebasestorage.app',
    iosBundleId: 'com.example.ltbq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChr3tgmwgzlj2sT9Te9tzBZYOnrgKyOIs',
    appId: '1:797973623484:ios:57ba308e488485b90656b9',
    messagingSenderId: '797973623484',
    projectId: 'ltb-10',
    storageBucket: 'ltb-10.firebasestorage.app',
    iosBundleId: 'com.example.ltbq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9ZznEAcSRWU3i5C3yAh8FeWfPgTBIlW0',
    appId: '1:797973623484:web:f3f88fec1d9b893b0656b9',
    messagingSenderId: '797973623484',
    projectId: 'ltb-10',
    authDomain: 'ltb-10.firebaseapp.com',
    storageBucket: 'ltb-10.firebasestorage.app',
  );
}
